### ISSUE TITLE
Numeriek zoeken 

### ISSUE THREAD

**Issue by xanderClaessens** [vives-project-xp/GreenhouseSecurity#19]
Numeriek zoeken die waterdicht, draadloos en bedraad kan werken.

**Comment by xanderClaessens** [comment]
We zullen voor een plaat kiezen om de numeriek te bevestigen zo is er geen probleem met een schuifdeur

**Comment by Belgianwafflecorp** [comment]
https://www.kiwi-electronics.com/nl/3x4-phone-style-matrix-keypad-2907?search=keypad%20matrix
